CREATE TABLE IF NOT EXISTS PRODUCT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOADED_MONEY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    amount VARCHAR(12) NOT NULL UNIQUE,
    quantity INT NOT NULL
);